[project]
name = "jobs_hk"
version = "1.0"
dependencies = [
    "requests",
    "bs4",
    "sqlalchemy",
    "sqlmodel",
    "pydantic",
    "ollama",
    "mcp[cli]",
]

[project.scripts]
run-ask = "jobs_hk.cli.ask:run"
run-search-job = "jobs_hk.cli.search_jobs:run"
run-search-job-MT = "jobs_hk.cli.search_jobs_multi_thread:run"
run-fill-job = "jobs_hk.cli.fill_jobs:run"
run-fill-job-MT = "jobs_hk.cli.fill_jobs_multi_threads:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "debugpy",
]
